import { useEffect, useMemo, useState } from "react";
import api from "../api/axios";

// ========================================
// TYPES
// ========================================

interface Table {
    table_name: string;
}

interface TableData {
    [key: string]: any;
}

interface ColumnInfo {
    column_name: string;
    data_type: string;
    is_nullable: string;
    column_default: string | null;
    is_identity: string;
    is_primary_key: boolean;
}

interface TableInfo {
    table: {
        table_name: string;
        table_type: string;
    };
    columns: ColumnInfo[];
}

interface Pagination {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
}

// ========================================
// HELPERS
// ========================================

const isAutoGeneratedColumn = (
    column: ColumnInfo
) => {
    return (
        column.is_identity === "YES" ||
        Boolean(
            column.column_default &&
            column.column_default.includes(
                "nextval"
            )
        )
    );
};

const getInputType = (dataType: string) => {
    const type = dataType.toLowerCase();

    if (
        type.includes("integer") ||
        type.includes("numeric") ||
        type.includes("double") ||
        type.includes("real") ||
        type.includes("decimal")
    ) {
        return "number";
    }

    if (
        type.includes("date") ||
        type.includes("timestamp")
    ) {
        return "text";
    }

    if (type.includes("boolean")) {
        return "checkbox";
    }

    return "text";
};

function Database() {

    // ========================================
    // TABEL
    // ========================================

    const [tables, setTables] =
        useState<Table[]>([]);

    const [selectedTable, setSelectedTable] =
        useState("");

    const [tableInfo, setTableInfo] =
        useState<TableInfo | null>(null);

    // ========================================
    // DATA
    // ========================================

    const [data, setData] =
        useState<TableData[]>([]);

    const [pagination, setPagination] =
        useState<Pagination | null>(null);

    // ========================================
    // SEARCH
    // ========================================

    const [search, setSearch] =
        useState("");

    // ========================================
    // LOADING
    // ========================================

    const [loadingTables, setLoadingTables] =
        useState(true);

    const [loadingData, setLoadingData] =
        useState(false);

    const [saving, setSaving] =
        useState(false);

    const [deleting, setDeleting] =
        useState(false);

    // ========================================
    // FORM
    // ========================================

    const [showModal, setShowModal] =
        useState(false);

    const [editingRow, setEditingRow] =
        useState<TableData | null>(null);

    const [formData, setFormData] =
        useState<TableData>({});

    // ========================================
    // USER / ROLE
    // ========================================

    const user = useMemo(() => {
        try {
            return JSON.parse(
                localStorage.getItem("user") || "null"
            );
        } catch {
            return null;
        }
    }, []);

    const isAdmin =
        user?.role === "admin";

    // ========================================
    // PRIMARY KEY
    // ========================================

    const primaryKey = useMemo(() => {
        if (!tableInfo) {
            return null;
        }

        const pk = tableInfo.columns.find(
            (column) =>
                column.is_primary_key === true
        );

        return pk?.column_name || null;
    }, [tableInfo]);

    // ========================================
    // LOAD ALL TABLES
    // ========================================

    useEffect(() => {
        loadTables();
    }, []);

    const loadTables = async () => {
        try {
            setLoadingTables(true);

            const response =
                await api.get("/tables");

            setTables(
                response.data || []
            );
        } catch (error) {
            console.error(
                "Gagal mengambil daftar tabel:",
                error
            );
        } finally {
            setLoadingTables(false);
        }
    };

    // ========================================
    // LOAD TABLE INFO
    // ========================================

    const loadTableInfo = async (
        tableName: string
    ) => {
        const response =
            await api.get(
                `/tables/${encodeURIComponent(
                    tableName
                )}/info`
            );

        setTableInfo(
            response.data
        );

        return response.data;
    };

    // ========================================
    // LOAD TABLE DATA
    // ========================================

    const loadTableData = async (
        tableName: string,
        page = 1,
        searchValue = ""
    ) => {

        if (!tableName) {
            return;
        }

        try {
            setLoadingData(true);

            const response =
                await api.get(
                    `/tables/${encodeURIComponent(
                        tableName
                    )}`,
                    {
                        params: {
                            page,
                            limit: 20,
                            search: searchValue,
                        },
                    }
                );

            setData(
                response.data.data || []
            );

            setPagination(
                response.data.pagination || null
            );

        } catch (error) {

            console.error(
                "Gagal mengambil data tabel:",
                error
            );

            setData([]);
            setPagination(null);

        } finally {

            setLoadingData(false);

        }
    };

    // ========================================
    // SELECT TABLE
    // ========================================

    const handleSelectTable = async (
        tableName: string
    ) => {

        setSelectedTable(
            tableName
        );

        setSearch("");

        setData([]);

        setPagination(null);

        setTableInfo(null);

        closeModal();

        if (!tableName) {
            return;
        }

        try {

            setLoadingData(true);

            await loadTableInfo(
                tableName
            );

            await loadTableData(
                tableName,
                1,
                ""
            );

        } catch (error) {

            console.error(
                "Gagal memilih tabel:",
                error
            );

            setTableInfo(null);
            setData([]);

        } finally {

            setLoadingData(false);

        }
    };

    // ========================================
    // SEARCH
    // ========================================

    const handleSearch = async () => {

        if (!selectedTable) {
            return;
        }

        await loadTableData(
            selectedTable,
            1,
            search
        );
    };

    // ========================================
    // RESET SEARCH
    // ========================================

    const handleResetSearch = async () => {

        if (!selectedTable) {
            return;
        }

        setSearch("");

        await loadTableData(
            selectedTable,
            1,
            ""
        );
    };

    // ========================================
    // PAGE CHANGE
    // ========================================

    const handlePageChange = async (
        page: number
    ) => {

        if (!selectedTable) {
            return;
        }

        if (!pagination) {
            return;
        }

        if (
            page < 1 ||
            page > pagination.totalPages
        ) {
            return;
        }

        await loadTableData(
            selectedTable,
            page,
            search
        );
    };

    // ========================================
    // FORM OPEN - ADD
    // ========================================

    const openAddModal = () => {

        if (!isAdmin) {
            alert(
                "Anda tidak memiliki izin untuk menambah data."
            );

            return;
        }

        if (!tableInfo) {
            return;
        }

        const initialData: TableData = {};

        tableInfo.columns.forEach(
            (column) => {

                if (
                    isAutoIncrementColumn(
                        column
                    )
                ) {
                    return;
                }

                if (
                    getInputType(
                        column.data_type
                    ) === "checkbox"
                ) {
                    initialData[
                        column.column_name
                    ] = false;
                } else {
                    initialData[
                        column.column_name
                    ] = "";
                }
            }
        );

        setEditingRow(null);

        setFormData(
            initialData
        );

        setShowModal(true);
    };

    // ========================================
    // FORM OPEN - EDIT
    // ========================================

    const openEditModal = (
        row: TableData
    ) => {

        if (!isAdmin) {
            alert(
                "Anda tidak memiliki izin untuk mengedit data."
            );

            return;
        }

        setEditingRow(
            row
        );

        const editData: TableData = {};

        tableInfo?.columns.forEach(
            (column) => {

                editData[
                    column.column_name
                ] =
                    row[
                        column.column_name
                    ] ?? "";

            }
        );

        setFormData(
            editData
        );

        setShowModal(true);
    };

    // ========================================
    // FORM CHANGE
    // ========================================

    const handleFormChange = (
        column: ColumnInfo,
        value: any
    ) => {

        setFormData(
            (previous) => ({
                ...previous,
                [column.column_name]:
                    value,
            })
        );
    };

    // ========================================
    // PREPARE PAYLOAD
    // ========================================

    const preparePayload = () => {

        if (!tableInfo) {
            return {};
        }

        const payload: TableData = {};

        tableInfo.columns.forEach(
            (column) => {

                // Saat insert, jangan kirim
                // auto increment.
                if (
                    !editingRow &&
                    isAutoIncrementColumn(
                        column
                    )
                ) {
                    return;
                }

                // Saat update, jangan kirim
                // primary key.
                if (
                    editingRow &&
                    column.is_primary_key
                ) {
                    return;
                }

                let value =
                    formData[
                        column.column_name
                    ];

                // String kosong untuk kolom
                // nullable lebih aman dikirim
                // sebagai null.
                if (
                    value === "" &&
                    column.is_nullable === "YES"
                ) {
                    value = null;
                }

                payload[
                    column.column_name
                ] = value;
            }
        );

        return payload;
    };

    // ========================================
    // SUBMIT FORM
    // ========================================

    const handleSubmit = async (
        event: React.FormEvent
    ) => {

        event.preventDefault();

        if (!isAdmin) {
            alert(
                "Anda tidak memiliki izin."
            );

            return;
        }

        if (!selectedTable) {
            return;
        }

        try {

            setSaving(true);

            const payload =
                preparePayload();

            // =================================
            // UPDATE
            // =================================

            if (editingRow) {

                if (!primaryKey) {

                    alert(
                        "Tabel ini tidak memiliki primary key."
                    );

                    return;
                }

                const id =
                    editingRow[
                        primaryKey
                    ];

                await api.put(
                    `/tables/${encodeURIComponent(
                        selectedTable
                    )}/${encodeURIComponent(
                        id
                    )}`,
                    payload
                );

                alert(
                    "Data berhasil diperbarui."
                );

            }

            // =================================
            // INSERT
            // =================================

            else {

                await api.post(
                    `/tables/${encodeURIComponent(
                        selectedTable
                    )}`,
                    payload
                );

                alert(
                    "Data berhasil ditambahkan."
                );
            }

            closeModal();

            await loadTableData(
                selectedTable,
                pagination?.page || 1,
                search
            );

        } catch (error: any) {

            console.error(
                "Gagal menyimpan data:",
                error
            );

            const message =
                error?.response?.data?.error ||
                error?.response?.data?.message ||
                "Gagal menyimpan data.";

            alert(message);

        } finally {

            setSaving(false);

        }
    };

    // ========================================
    // DELETE
    // ========================================

    const handleDelete = async (
        row: TableData
    ) => {

        if (!isAdmin) {
            alert(
                "Anda tidak memiliki izin untuk menghapus data."
            );

            return;
        }

        if (!selectedTable) {
            return;
        }

        if (!primaryKey) {

            alert(
                "Tabel ini tidak memiliki primary key, sehingga data tidak dapat dihapus melalui interface ini."
            );

            return;
        }

        const id =
            row[primaryKey];

        if (
            id === null ||
            id === undefined
        ) {

            alert(
                "Primary key data tidak ditemukan."
            );

            return;
        }

        const confirmed =
            window.confirm(
                `Yakin ingin menghapus data dengan ${primaryKey} = ${id}?`
            );

        if (!confirmed) {
            return;
        }

        try {

            setDeleting(true);

            await api.delete(
                `/tables/${encodeURIComponent(
                    selectedTable
                )}/${encodeURIComponent(
                    id
                )}`
            );

            alert(
                "Data berhasil dihapus."
            );

            await loadTableData(
                selectedTable,
                pagination?.page || 1,
                search
            );

        } catch (error: any) {

            console.error(
                "Gagal menghapus data:",
                error
            );

            const message =
                error?.response?.data?.error ||
                error?.response?.data?.message ||
                "Gagal menghapus data.";

            alert(message);

        } finally {

            setDeleting(false);

        }
    };

    // ========================================
    // CLOSE MODAL
    // ========================================

    const closeModal = () => {

        setShowModal(false);

        setEditingRow(null);

        setFormData({});
    };

    // ========================================
    // PAGE NUMBERS
    // ========================================

    const pageNumbers = useMemo(() => {

        if (!pagination) {
            return [];
        }

        const totalPages =
            pagination.totalPages;

        const currentPage =
            pagination.page;

        const maxVisible = 7;

        if (
            totalPages <= maxVisible
        ) {

            return Array.from(
                {
                    length: totalPages,
                },
                (_, index) =>
                    index + 1
            );

        }

        let start =
            Math.max(
                1,
                currentPage - 3
            );

        let end =
            Math.min(
                totalPages,
                currentPage + 3
            );

        if (currentPage <= 3) {
            start = 1;
            end = 7;
        }

        if (
            currentPage >=
            totalPages - 2
        ) {
            start =
                totalPages - 6;

            end =
                totalPages;
        }

        return Array.from(
            {
                length:
                    end - start + 1,
            },
            (_, index) =>
                start + index
        );

    }, [pagination]);

    // ========================================
    // RENDER
    // ========================================

    return (

        <div className="flex min-h-full min-w-0 bg-gray-100">

            {/* =================================
                SIDEBAR TABLE
            ================================= */}

            <aside className="w-72 min-w-72 bg-white p-5 shadow-sm">

                <div className="mb-6">

                    <h1 className="text-xl font-bold text-gray-800">
                        Database Explorer
                    </h1>

                    <p className="mt-1 text-sm text-gray-500">
                        PostgreSQL
                    </p>

                </div>

                {loadingTables ? (

                    <p className="text-sm text-gray-500">
                        Memuat tabel...
                    </p>

                ) : tables.length === 0 ? (

                    <p className="text-sm text-gray-500">
                        Tidak ada tabel.
                    </p>

                ) : (

                    <div className="space-y-1">

                        {tables.map(
                            (table) => (

                                <button
                                    key={
                                        table.table_name
                                    }
                                    onClick={() =>
                                        handleSelectTable(
                                            table.table_name
                                        )
                                    }
                                    className={`w-full rounded-lg px-3 py-2 text-left text-sm transition ${
                                        selectedTable ===
                                        table.table_name
                                            ? "bg-blue-600 font-semibold text-white"
                                            : "text-gray-700 hover:bg-gray-100"
                                    }`}
                                >
                                    {
                                        table.table_name
                                    }
                                </button>

                            )
                        )}

                    </div>

                )}

            </aside>


            {/* =================================
                MAIN
            ================================= */}

            <main className="min-w-0 flex-1 p-6 md:p-8">

                {!selectedTable ? (

                    <div>

                        <h2 className="text-2xl font-bold text-gray-800">
                            Database
                        </h2>

                        <p className="mt-2 text-gray-500">
                            Pilih tabel di sebelah kiri
                            untuk melihat dan mengelola
                            data.
                        </p>

                    </div>

                ) : (

                    <>

                        {/* =========================
                            HEADER
                        ========================= */}

                        <div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-center">

                            <div>

                                <h2 className="text-2xl font-bold text-gray-800">
                                    {
                                        selectedTable
                                    }
                                </h2>

                                <p className="mt-1 text-sm text-gray-500">
                                    Tipe:{" "}
                                    {
                                        tableInfo?.table
                                            .table_type ||
                                        "-"
                                    }
                                    {" • "}
                                    Primary Key:{" "}
                                    {
                                        primaryKey ||
                                        "Tidak ada"
                                    }
                                </p>

                            </div>


                            {/* ADMIN ACTION */}

                            {isAdmin && (

                                <button
                                    onClick={
                                        openAddModal
                                    }
                                    className="rounded-lg bg-blue-600 px-4 py-2 font-medium text-white transition hover:bg-blue-700"
                                >
                                    + Tambah Data
                                </button>

                            )}

                        </div>


                        {/* =========================
                            TABLE INFO
                        ========================= */}

                        {tableInfo && (

                            <div className="mb-6 rounded-xl bg-white p-5 shadow-sm">

                                <h3 className="mb-4 font-semibold text-gray-800">
                                    Struktur Tabel
                                </h3>

                                <div className="overflow-x-auto">

                                    <table className="w-full min-w-[700px] border-collapse">

                                        <thead>

                                            <tr className="bg-gray-50">

                                                <th className="border p-3 text-left text-sm">
                                                    Kolom
                                                </th>

                                                <th className="border p-3 text-left text-sm">
                                                    Tipe
                                                </th>

                                                <th className="border p-3 text-center text-sm">
                                                    Primary Key
                                                </th>

                                                <th className="border p-3 text-center text-sm">
                                                    Nullable
                                                </th>

                                                <th className="border p-3 text-left text-sm">
                                                    Default
                                                </th>

                                            </tr>

                                        </thead>

                                        <tbody>

                                            {tableInfo.columns.map(
                                                (column) => (

                                                    <tr
                                                        key={
                                                            column.column_name
                                                        }
                                                    >

                                                        <td className="border p-3 text-sm">
                                                            {
                                                                column.column_name
                                                            }
                                                        </td>

                                                        <td className="border p-3 text-sm">
                                                            {
                                                                column.data_type
                                                            }
                                                        </td>

                                                        <td className="border p-3 text-center text-sm">
                                                            {column.is_primary_key
                                                                ? "✓"
                                                                : "-"}
                                                        </td>

                                                        <td className="border p-3 text-center text-sm">
                                                            {
                                                                column.is_nullable
                                                            }
                                                        </td>

                                                        <td className="border p-3 text-sm">
                                                            {
                                                                column.column_default ||
                                                                "-"
                                                            }
                                                        </td>

                                                    </tr>

                                                )
                                            )}

                                        </tbody>

                                    </table>

                                </div>

                            </div>

                        )}


                        {/* =========================
                            SEARCH
                        ========================= */}

                        <div className="mb-6 flex flex-col gap-3 sm:flex-row">

                            <input
                                type="text"
                                placeholder="Cari data..."
                                value={search}
                                onChange={(e) =>
                                    setSearch(
                                        e.target.value
                                    )
                                }
                                onKeyDown={(
                                    e
                                ) => {

                                    if (
                                        e.key ===
                                        "Enter"
                                    ) {
                                        handleSearch();
                                    }

                                }}
                                className="w-full rounded-lg border bg-white px-4 py-2 outline-none focus:border-blue-500 sm:w-80"
                            />

                            <button
                                onClick={
                                    handleSearch
                                }
                                className="rounded-lg bg-blue-600 px-4 py-2 font-medium text-white hover:bg-blue-700"
                            >
                                Cari
                            </button>

                            <button
                                onClick={
                                    handleResetSearch
                                }
                                className="rounded-lg border bg-white px-4 py-2 font-medium text-gray-700 hover:bg-gray-50"
                            >
                                Reset
                            </button>

                        </div>


                        {/* =========================
                            DATA TABLE
                        ========================= */}

                        <div className="rounded-xl bg-white shadow-sm">

                            {loadingData ? (

                                <div className="p-10 text-center text-gray-500">
                                    Memuat data...
                                </div>

                            ) : data.length === 0 ? (

                                <div className="p-10 text-center text-gray-500">
                                    Tidak ada data.
                                </div>

                            ) : (

                                <div className="overflow-x-auto">

                                    <table className="w-full min-w-max border-collapse">

                                        <thead>

                                            <tr className="bg-gray-50">

                                                {Object.keys(
                                                    data[0]
                                                ).map(
                                                    (
                                                        column
                                                    ) => (

                                                        <th
                                                            key={
                                                                column
                                                            }
                                                            className="border-b p-3 text-left text-sm font-semibold text-gray-700"
                                                        >
                                                            {
                                                                column
                                                            }
                                                        </th>

                                                    )
                                                )}

                                                {isAdmin && (

                                                    <th className="border-b p-3 text-left text-sm font-semibold text-gray-700">
                                                        Aksi
                                                    </th>

                                                )}

                                            </tr>

                                        </thead>


                                        <tbody>

                                            {data.map(
                                                (
                                                    row,
                                                    index
                                                ) => (

                                                    <tr
                                                        key={
                                                            index
                                                        }
                                                        className="hover:bg-gray-50"
                                                    >

                                                        {Object.keys(
                                                            data[0]
                                                        ).map(
                                                            (
                                                                column
                                                            ) => (

                                                                <td
                                                                    key={
                                                                        column
                                                                    }
                                                                    className="border-b p-3 text-sm text-gray-700"
                                                                >

                                                                    {row[
                                                                        column
                                                                    ] !==
                                                                    null &&
                                                                    row[
                                                                        column
                                                                    ] !==
                                                                    undefined
                                                                        ? String(
                                                                              row[
                                                                                  column
                                                                              ]
                                                                          )
                                                                        : "-"}

                                                                </td>

                                                            )
                                                        )}


                                                        {isAdmin && (

                                                            <td className="border-b p-3">

                                                                <div className="flex gap-2">

                                                                    <button
                                                                        onClick={() =>
                                                                            openEditModal(
                                                                                row
                                                                            )
                                                                        }
                                                                        disabled={
                                                                            deleting
                                                                        }
                                                                        className="rounded-md bg-yellow-500 px-3 py-1.5 text-sm font-medium text-white hover:bg-yellow-600 disabled:opacity-50"
                                                                    >
                                                                        Edit
                                                                    </button>


                                                                    <button
                                                                        onClick={() =>
                                                                            handleDelete(
                                                                                row
                                                                            )
                                                                        }
                                                                        disabled={
                                                                            deleting
                                                                        }
                                                                        className="rounded-md bg-red-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-50"
                                                                    >
                                                                        Hapus
                                                                    </button>

                                                                </div>

                                                            </td>

                                                        )}

                                                    </tr>

                                                )
                                            )}

                                        </tbody>

                                    </table>

                                </div>

                            )}

                        </div>


                        {/* =========================
                            PAGINATION
                        ========================= */}

                        {pagination && (
                            <div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">

                                <p className="text-sm text-gray-500">

                                    Menampilkan{" "}
                                    {data.length}{" "}
                                    dari{" "}
                                    {pagination.total}{" "}
                                    data

                                </p>


                                <div className="flex items-center gap-1">

                                    <button
                                        disabled={
                                            pagination.page <=
                                            1
                                        }
                                        onClick={() =>
                                            handlePageChange(
                                                pagination.page -
                                                    1
                                            )
                                        }
                                        className="rounded-md border bg-white px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-40"
                                    >
                                        ←
                                    </button>


                                    {pageNumbers.map(
                                        (pageNumber) => (

                                            <button
                                                key={
                                                    pageNumber
                                                }
                                                onClick={() =>
                                                    handlePageChange(
                                                        pageNumber
                                                    )
                                                }
                                                className={`rounded-md border px-3 py-2 text-sm ${
                                                    pagination.page ===
                                                    pageNumber
                                                        ? "border-blue-600 bg-blue-600 text-white"
                                                        : "bg-white text-gray-700 hover:bg-gray-50"
                                                }`}
                                            >
                                                {
                                                    pageNumber
                                                }
                                            </button>

                                        )
                                    )}


                                    <button
                                        disabled={
                                            pagination.page >=
                                            pagination.totalPages
                                        }
                                        onClick={() =>
                                            handlePageChange(
                                                pagination.page +
                                                    1
                                            )
                                        }
                                        className="rounded-md border bg-white px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-40"
                                    >
                                        →
                                    </button>

                                </div>

                            </div>
                        )}

                    </>

                )}

            </main>


            {/* =================================
                MODAL ADD / EDIT
            ================================= */}

            {showModal &&
                tableInfo && (

                    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">

                        <div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl">

                            {/* HEADER */}

                            <div className="mb-6 flex items-center justify-between">

                                <div>

                                    <h2 className="text-xl font-bold text-gray-800">
                                        {editingRow
                                            ? "Edit Data"
                                            : "Tambah Data"}
                                    </h2>

                                    <p className="mt-1 text-sm text-gray-500">
                                        {
                                            selectedTable
                                        }
                                    </p>

                                </div>


                                <button
                                    onClick={
                                        closeModal
                                    }
                                    className="rounded-lg px-3 py-2 text-gray-500 hover:bg-gray-100"
                                >
                                    ✕
                                </button>

                            </div>


                            {/* FORM */}

                            <form
                                onSubmit={
                                    handleSubmit
                                }
                            >

                                <div className="space-y-4">

                                    {tableInfo.columns.map(
                                        (column) => {

                                            const autoIncrement =
                                                isAutoIncrementColumn(
                                                    column
                                                );

                                            const inputType =
                                                getInputType(
                                                    column.data_type
                                                );

                                            // Jangan tampilkan
                                            // sequence primary key
                                            // ketika INSERT.
                                            if (
                                                !editingRow &&
                                                autoIncrement
                                            ) {
                                                return null;
                                            }

                                            const isPrimaryKey =
                                                column.is_primary_key;

                                            const disabled =
                                                Boolean(
                                                    editingRow &&
                                                    isPrimaryKey
                                                );

                                            return (

                                                <div
                                                    key={
                                                        column.column_name
                                                    }
                                                >

                                                    <label className="mb-1 block text-sm font-semibold text-gray-700">

                                                        {
                                                            column.column_name
                                                        }

                                                        {column.is_nullable ===
                                                            "NO" &&
                                                            !isPrimaryKey && (
                                                                <span className="text-red-500">
                                                                    {" "}
                                                                    *
                                                                </span>
                                                            )}

                                                    </label>


                                                    {inputType ===
                                                    "checkbox" ? (

                                                        <label className="flex items-center gap-2">

                                                            <input
                                                                type="checkbox"
                                                                checked={
                                                                    Boolean(
                                                                        formData[
                                                                            column.column_name
                                                                        ]
                                                                    )
                                                                }
                                                                disabled={
                                                                    disabled
                                                                }
                                                                onChange={(
                                                                    e
                                                                ) =>
                                                                    handleFormChange(
                                                                        column,
                                                                        e
                                                                            .target
                                                                            .checked
                                                                    )
                                                                }
                                                                className="h-4 w-4"
                                                            />

                                                            <span className="text-sm text-gray-600">
                                                                {
                                                                    formData[
                                                                        column
                                                                            .column_name
                                                                    ]
                                                                        ? "True"
                                                                        : "False"
                                                                }
                                                            </span>

                                                        </label>

                                                    ) : column.data_type
                                                        .toLowerCase()
                                                        .includes(
                                                            "text"
                                                        ) ? (

                                                        <textarea
                                                            value={
                                                                formData[
                                                                    column
                                                                        .column_name
                                                                ] ??
                                                                ""
                                                            }
                                                            disabled={
                                                                disabled
                                                            }
                                                            onChange={(
                                                                e
                                                            ) =>
                                                                handleFormChange(
                                                                    column,
                                                                    e.target
                                                                        .value
                                                                )
                                                            }
                                                            rows={3}
                                                            className="w-full rounded-lg border px-3 py-2 outline-none focus:border-blue-500 disabled:bg-gray-100"
                                                        />

                                                    ) : (

                                                        <input
                                                            type={
                                                                inputType
                                                            }
                                                            value={
                                                                formData[
                                                                    column
                                                                        .column_name
                                                                ] ??
                                                                ""
                                                            }
                                                            disabled={
                                                                disabled
                                                            }
                                                            onChange={(
                                                                e
                                                            ) =>
                                                                handleFormChange(
                                                                    column,
                                                                    e.target
                                                                        .value
                                                                )
                                                            }
                                                            className="w-full rounded-lg border px-3 py-2 outline-none focus:border-blue-500 disabled:bg-gray-100"
                                                        />

                                                    )}

                                                    {disabled && (
                                                        <p className="mt-1 text-xs text-gray-400">
                                                            Primary key
                                                            tidak dapat
                                                            diubah.
                                                        </p>
                                                    )}

                                                </div>

                                            );

                                        }
                                    )}

                                </div>


                                {/* BUTTON */}

                                <div className="mt-6 flex justify-end gap-3">

                                    <button
                                        type="button"
                                        onClick={
                                            closeModal
                                        }
                                        disabled={
                                            saving
                                        }
                                        className="rounded-lg border px-4 py-2 text-gray-700 hover:bg-gray-50"
                                    >
                                        Batal
                                    </button>


                                    <button
                                        type="submit"
                                        disabled={
                                            saving
                                        }
                                        className="rounded-lg bg-blue-600 px-4 py-2 font-medium text-white hover:bg-blue-700 disabled:opacity-50"
                                    >
                                        {saving
                                            ? "Menyimpan..."
                                            : editingRow
                                            ? "Simpan Perubahan"
                                            : "Tambah Data"}
                                    </button>

                                </div>

                            </form>

                        </div>

                    </div>

                )}

        </div>
    );
}

export default Database;